FROM node:23.11.0-alpine AS build

WORKDIR /api

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build




FROM node:23.11.0-alpine AS runner

WORKDIR /api

COPY --from=build /api/dist ./src
COPY --from=build /api/node_modules ./node_modules
COPY --from=build /api/package.json ./package.json

EXPOSE 4000

CMD ["yarn", "serve"]